-- GDPR right-to-be-forgotten: soft-delete for Employee
-- Adds deletedAt/deletedById/deletionReason columns to Employee.
-- All FK relations from child tables (Expense, Document, MedicalReview,
-- Training, Vacation, ContractExtension, OvertimeEntry, Onboarding,
-- ProjectWork, ChecklistTask, EmergencyContact, EmployeeVacationBalance,
-- TimeEntry) are changed from ON DELETE CASCADE to ON DELETE RESTRICT,
-- forcing an explicit purge step (see scripts/purge-soft-deleted-employees.ts).

-- Add soft-delete columns
ALTER TABLE "Employee"
    ADD COLUMN "deletedAt" TIMESTAMP(3),
    ADD COLUMN "deletedById" TEXT,
    ADD COLUMN "deletionReason" TEXT;

-- Index for fast "active vs deleted" filtering
CREATE INDEX "Employee_deletedAt_idx" ON "Employee"("deletedAt");

-- Drop destructive FKs and recreate as RESTRICT.
-- The constraint names below match the names generated by Prisma
-- (singular model name + column name + "_fkey"). They are case-sensitive
-- in PostgreSQL. If a migration has previously renamed them, you may
-- need to inspect the live schema with:
--   SELECT conname FROM pg_constraint WHERE conrelid = '"Employee"'::regclass;
-- ===========================================================================

-- Expense
ALTER TABLE "Expense" DROP CONSTRAINT IF EXISTS "Expense_employeeId_fkey";
ALTER TABLE "Expense"
    ADD CONSTRAINT "Expense_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE NO ACTION;

-- Document
ALTER TABLE "Document" DROP CONSTRAINT IF EXISTS "Document_employeeId_fkey";
ALTER TABLE "Document"
    ADD CONSTRAINT "Document_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE NO ACTION;

-- MedicalReview
ALTER TABLE "MedicalReview" DROP CONSTRAINT IF EXISTS "MedicalReview_employeeId_fkey";
ALTER TABLE "MedicalReview"
    ADD CONSTRAINT "MedicalReview_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE NO ACTION;

-- Training
ALTER TABLE "Training" DROP CONSTRAINT IF EXISTS "Training_employeeId_fkey";
ALTER TABLE "Training"
    ADD CONSTRAINT "Training_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- Vacation
ALTER TABLE "Vacation" DROP CONSTRAINT IF EXISTS "Vacation_employeeId_fkey";
ALTER TABLE "Vacation"
    ADD CONSTRAINT "Vacation_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- ContractExtension
ALTER TABLE "ContractExtension" DROP CONSTRAINT IF EXISTS "ContractExtension_employeeId_fkey";
ALTER TABLE "ContractExtension"
    ADD CONSTRAINT "ContractExtension_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE NO ACTION;

-- OvertimeEntry
ALTER TABLE "OvertimeEntry" DROP CONSTRAINT IF EXISTS "OvertimeEntry_employeeId_fkey";
ALTER TABLE "OvertimeEntry"
    ADD CONSTRAINT "OvertimeEntry_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- EmployeeOnboarding
ALTER TABLE "EmployeeOnboarding" DROP CONSTRAINT IF EXISTS "EmployeeOnboarding_employeeId_fkey";
ALTER TABLE "EmployeeOnboarding"
    ADD CONSTRAINT "EmployeeOnboarding_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE NO ACTION;

-- EmployeeProjectWork
ALTER TABLE "EmployeeProjectWork" DROP CONSTRAINT IF EXISTS "EmployeeProjectWork_employeeId_fkey";
ALTER TABLE "EmployeeProjectWork"
    ADD CONSTRAINT "EmployeeProjectWork_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE NO ACTION;

-- ChecklistTask
ALTER TABLE "ChecklistTask" DROP CONSTRAINT IF EXISTS "ChecklistTask_employeeId_fkey";
ALTER TABLE "ChecklistTask"
    ADD CONSTRAINT "ChecklistTask_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE NO ACTION;

-- EmergencyContact
ALTER TABLE "EmergencyContact" DROP CONSTRAINT IF EXISTS "EmergencyContact_employeeId_fkey";
ALTER TABLE "EmergencyContact"
    ADD CONSTRAINT "EmergencyContact_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- EmployeeVacationBalance
ALTER TABLE "EmployeeVacationBalance" DROP CONSTRAINT IF EXISTS "EmployeeVacationBalance_employeeId_fkey";
ALTER TABLE "EmployeeVacationBalance"
    ADD CONSTRAINT "EmployeeVacationBalance_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- TimeEntry
ALTER TABLE "TimeEntry" DROP CONSTRAINT IF EXISTS "TimeEntry_employeeId_fkey";
ALTER TABLE "TimeEntry"
    ADD CONSTRAINT "TimeEntry_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;
