import { beforeEach, describe, expect, it, vi } from 'vitest';

const { tx, prismaMock } = vi.hoisted(() => {
    const transactionClient = {
        hrTask: {
            upsert: vi.fn(),
            updateMany: vi.fn()
        }
    };
    return {
        tx: transactionClient,
        prismaMock: {
            company: { findUnique: vi.fn() },
            hrAlertRule: { createMany: vi.fn(), findMany: vi.fn(), findUnique: vi.fn(), update: vi.fn() },
            employee: { findMany: vi.fn(), findUnique: vi.fn() },
            document: { findMany: vi.fn() },
            vacation: { findMany: vi.fn(), count: vi.fn() },
            inboxDocument: { findMany: vi.fn(), count: vi.fn() },
            hrTask: { findMany: vi.fn(), findUnique: vi.fn(), count: vi.fn(), create: vi.fn(), update: vi.fn() },
            expense: { count: vi.fn() },
            anomalyEvent: { count: vi.fn() },
            payrollRow: { count: vi.fn() },
            employmentPeriod: { count: vi.fn() },
            gestoriaPeriod: { findUnique: vi.fn() },
            hrAlertDelivery: { count: vi.fn(), findFirst: vi.fn() },
            hrMonthlyClose: { findUnique: vi.fn(), upsert: vi.fn(), update: vi.fn() },
            $transaction: vi.fn(async (callback: (client: typeof transactionClient) => unknown) => callback(transactionClient))
        }
    };
});

vi.mock('../lib/prisma', () => ({ prisma: prismaMock }));
vi.mock('./HrAlertEmailService', () => ({
    HrAlertEmailService: { processCompany: vi.fn().mockResolvedValue({ sent: 0, failed: 0, skipped: 0 }) }
}));
vi.mock('./EmailService', () => ({
    EmailService: { isConfigured: vi.fn().mockResolvedValue(true) }
}));

import { HrWorkspaceService } from './HrWorkspaceService';

const actor = {
    id: 'user-1',
    email: 'rrhh@example.com',
    role: 'hr',
    companyId: 'company-1',
    permissions: { employees: 'write', reports: 'read', notifications: 'read' }
} as never;

describe('HrWorkspaceService', () => {
    beforeEach(() => {
        vi.clearAllMocks();
        prismaMock.company.findUnique.mockResolvedValue({ id: 'company-1' });
        prismaMock.hrAlertRule.createMany.mockResolvedValue({ count: 0 });
        prismaMock.document.findMany.mockResolvedValue([]);
        prismaMock.vacation.findMany.mockResolvedValue([]);
        prismaMock.inboxDocument.findMany.mockResolvedValue([]);
        tx.hrTask.updateMany.mockResolvedValue({ count: 0 });
    });

    it('creates an automatic task from an enabled contract expiry rule', async () => {
        prismaMock.hrAlertRule.findMany.mockResolvedValue([
            {
                id: 'rule-1',
                type: 'CONTRACT_EXPIRING',
                leadDays: 30,
                severity: 'HIGH',
                enabled: true
            }
        ]);
        prismaMock.employee.findMany.mockResolvedValue([
            {
                id: 'employee-1',
                name: 'Ana García',
                firstName: 'Ana',
                lastName: 'García',
                contractEndDate: new Date(Date.now() + 10 * 86400000),
                dniExpiration: null
            }
        ]);

        const result = await HrWorkspaceService.syncAutomaticTasks(actor, 'company-1');

        expect(result).toEqual({ synchronized: 1 });
        expect(tx.hrTask.upsert).toHaveBeenCalledWith(
            expect.objectContaining({
                where: { sourceKey: 'company-1:CONTRACT_EXPIRING:employee-1' },
                create: expect.objectContaining({
                    title: 'Decidir renovación de contrato',
                    priority: 'HIGH',
                    category: 'CONTRACTS',
                    autoGenerated: true
                })
            })
        );
    });

    it('builds a monthly close with unresolved items marked as blockers', async () => {
        prismaMock.vacation.count.mockResolvedValue(2);
        prismaMock.expense.count.mockResolvedValue(0);
        prismaMock.anomalyEvent.count.mockResolvedValue(1);
        prismaMock.payrollRow.count.mockResolvedValue(0);
        prismaMock.employmentPeriod.count.mockResolvedValue(0);
        prismaMock.inboxDocument.count.mockResolvedValue(0);
        prismaMock.hrTask.count.mockResolvedValue(0);
        prismaMock.gestoriaPeriod.findUnique.mockResolvedValue({ status: 'CLOSED' });
        prismaMock.hrMonthlyClose.findUnique.mockResolvedValue(null);
        prismaMock.hrMonthlyClose.upsert.mockImplementation(async (args: any) => ({
            id: 'close-1',
            ...args.create
        }));

        const close = await HrWorkspaceService.getMonthlyClose(actor, 'company-1', 2026, 7) as any;
        const items = close.items as Array<{ key: string; metric: number; blocking: boolean; completed: boolean }>;

        expect(items.find((item) => item.key === 'ABSENCES')).toEqual(
            expect.objectContaining({ metric: 2, blocking: true, completed: false })
        );
        expect(items.find((item) => item.key === 'ATTENDANCE')).toEqual(
            expect.objectContaining({ metric: 1, blocking: true, completed: false })
        );
        expect(items.find((item) => item.key === 'GESTORIA')).toEqual(
            expect.objectContaining({ metric: 0, completed: true })
        );
    });

    it('calculates missing requirements for the intelligent employee record', async () => {
        prismaMock.employee.findUnique.mockResolvedValue({
            id: 'employee-1',
            companyId: 'company-1',
            active: true,
            dni: '12345678Z',
            email: 'ana@example.com',
            phone: null,
            address: null,
            socialSecurityNumber: null,
            socialSecurityNumberEnc: null,
            iban: null,
            ibanEnc: 'encrypted',
            department: 'Obras',
            jobTitle: 'Oficial',
            contractType: 'Indefinido',
            entryDate: new Date('2024-01-01'),
            contractEndDate: null,
            dniExpiration: null,
            _count: { documents: 1, trainings: 0, medicalReviews: 0, assets: 1 }
        });
        prismaMock.document.findMany.mockResolvedValue([
            { id: 'doc-1', name: 'Contrato', category: 'LABORAL', expiryDate: null }
        ]);
        prismaMock.hrTask.findMany.mockResolvedValue([]);

        const record = await HrWorkspaceService.getSmartRecord(actor, 'employee-1');

        expect(record.score).toBeLessThan(100);
        expect(record.missing.map((item) => item.key)).toEqual(
            expect.arrayContaining(['phone', 'address', 'socialSecurity', 'prlDocument'])
        );
        expect(record.attention.some((item) => item.type === 'MISSING_DATA')).toBe(true);
    });
});
