
import { Request, Response } from 'express';
import { alertService } from '../services/AlertService';
import { AuthenticatedRequest } from '../types/express';
import { createLogger } from '../services/LoggerService';

const log = createLogger('AlertController');

export class AlertController {
    // GET /api/alerts - Get unread alerts
    async getAlerts(req: Request, res: Response) {
        try {
            // Alerts are now generated by SchedulerService

            const { user } = req as AuthenticatedRequest;
            const permissions = user?.role === 'admin' ? null : user?.permissions;

            const alerts = await alertService.getUnreadAlerts(permissions);
            res.json(alerts);
        } catch (error: any) {
            log.error({ error }, 'Error fetching alerts');
            res.status(500).json({ error: 'Failed to fetch alerts' });
        }
    }

    // PUT /api/alerts/:id/read - Mark as read
    async markAsRead(req: Request, res: Response) {
        try {
            const { id } = req.params;
            await alertService.markAsRead(id);
            res.json({ success: true });
        } catch (error) {
            res.status(500).json({ error: 'Failed to mark alert as read' });
        }
    }

    // PUT /api/alerts/:id/dismiss - Dismiss
    async dismiss(req: Request, res: Response) {
        try {
            const { id } = req.params;
            await alertService.dismissAlert(id);
            res.json({ success: true });
        } catch (error) {
            res.status(500).json({ error: 'Failed to dismiss alert' });
        }
    }
}

export const alertController = new AlertController();
