export interface CompanyScope {
    id: string;
    name: string;
}

export interface HrTask {
    id: string;
    companyId: string;
    employeeId?: string | null;
    title: string;
    description?: string | null;
    category: string;
    priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
    status: 'PENDING' | 'IN_PROGRESS' | 'BLOCKED' | 'COMPLETED' | 'DISMISSED';
    dueDate?: string | null;
    actionUrl?: string | null;
    autoGenerated: boolean;
    assignedTo?: { id: string; email: string } | null;
    employee?: {
        id: string;
        name: string;
        firstName?: string | null;
        lastName?: string | null;
        dni: string;
        department?: string | null;
    } | null;
}

export interface HrTaskOverview {
    tasks: HrTask[];
    summary: {
        pending: number;
        urgent: number;
        overdue: number;
        dueSoon: number;
        completedThisMonth: number;
    };
}

export interface HrAlertRule {
    id: string;
    companyId: string;
    type: string;
    name: string;
    description?: string | null;
    enabled: boolean;
    leadDays: number;
    severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
    channels: string;
    emailMode: 'IMMEDIATE' | 'DAILY_DIGEST';
    emailRecipients: string;
    emailIncludeHr: boolean;
    emailIncludeManager: boolean;
}

export interface HrAlertEmailStatus {
    configured: boolean;
    sent: number;
    failed: number;
    pending: number;
    lastDelivery?: {
        status: 'PENDING' | 'SENT' | 'FAILED';
        recipient: string;
        sentAt?: string | null;
        updatedAt: string;
        lastError?: string | null;
    } | null;
}

export interface MonthlyCloseItem {
    key: string;
    label: string;
    description: string;
    completed: boolean;
    required: boolean;
    metric: number;
    blocking: boolean;
    actionUrl: string;
}

export interface HrMonthlyClose {
    id: string;
    companyId: string;
    year: number;
    month: number;
    status: 'OPEN' | 'CLOSED';
    items: MonthlyCloseItem[];
    notes?: string | null;
    closedAt?: string | null;
    closedBy?: { id: string; email: string } | null;
}

export interface SmartRecord {
    score: number;
    completed: number;
    total: number;
    completedWeight: number;
    totalWeight: number;
    missing: Array<{ key: string; label: string; actionUrl: string }>;
    attention: Array<{
        id: string;
        type: string;
        severity: string;
        title: string;
        description: string;
        actionUrl: string;
    }>;
    tasks: Array<{
        id: string;
        title: string;
        priority: string;
        dueDate?: string | null;
        actionUrl?: string | null;
    }>;
    counts: {
        documents: number;
        trainings: number;
        medicalReviews: number;
        assets: number;
    };
}
