CREATE TABLE "HrTask" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "employeeId" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "category" TEXT NOT NULL,
    "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "dueDate" TIMESTAMP(3),
    "actionUrl" TEXT,
    "sourceType" TEXT,
    "sourceKey" TEXT,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB,
    "assignedToId" TEXT,
    "createdById" TEXT,
    "completedById" TEXT,
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "HrTask_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "HrAlertRule" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "leadDays" INTEGER NOT NULL DEFAULT 30,
    "severity" TEXT NOT NULL DEFAULT 'MEDIUM',
    "channels" TEXT NOT NULL DEFAULT '["IN_APP"]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "HrAlertRule_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "HrMonthlyClose" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "month" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'OPEN',
    "items" JSONB NOT NULL,
    "notes" TEXT,
    "closedAt" TIMESTAMP(3),
    "closedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "HrMonthlyClose_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "HrTask_sourceKey_key" ON "HrTask"("sourceKey");
CREATE INDEX "HrTask_companyId_status_dueDate_idx" ON "HrTask"("companyId", "status", "dueDate");
CREATE INDEX "HrTask_companyId_priority_status_idx" ON "HrTask"("companyId", "priority", "status");
CREATE INDEX "HrTask_employeeId_status_idx" ON "HrTask"("employeeId", "status");
CREATE INDEX "HrTask_assignedToId_status_idx" ON "HrTask"("assignedToId", "status");
CREATE UNIQUE INDEX "HrAlertRule_companyId_type_key" ON "HrAlertRule"("companyId", "type");
CREATE INDEX "HrAlertRule_companyId_enabled_idx" ON "HrAlertRule"("companyId", "enabled");
CREATE UNIQUE INDEX "HrMonthlyClose_companyId_year_month_key" ON "HrMonthlyClose"("companyId", "year", "month");
CREATE INDEX "HrMonthlyClose_companyId_status_idx" ON "HrMonthlyClose"("companyId", "status");

ALTER TABLE "HrTask" ADD CONSTRAINT "HrTask_companyId_fkey"
    FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HrTask" ADD CONSTRAINT "HrTask_employeeId_fkey"
    FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "HrTask" ADD CONSTRAINT "HrTask_assignedToId_fkey"
    FOREIGN KEY ("assignedToId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "HrTask" ADD CONSTRAINT "HrTask_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "HrTask" ADD CONSTRAINT "HrTask_completedById_fkey"
    FOREIGN KEY ("completedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "HrAlertRule" ADD CONSTRAINT "HrAlertRule_companyId_fkey"
    FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HrMonthlyClose" ADD CONSTRAINT "HrMonthlyClose_companyId_fkey"
    FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HrMonthlyClose" ADD CONSTRAINT "HrMonthlyClose_closedById_fkey"
    FOREIGN KEY ("closedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
