import type { Express } from 'express';
import { protect, checkPermission, requireGlobalAdmin } from '../middlewares/authMiddleware';
import employeeRoutes from '../routes/employeeRoutes';
import payrollRoutes from '../routes/payrollRoutes';
import mappingProfileRoutes from '../routes/mappingProfileRoutes';
import dashboardRoutes from '../routes/dashboardRoutes';
import vacationRoutes from '../routes/vacationRoutes';
import companyRoutes from '../routes/companyRoutes';
import auditRoutes from '../routes/auditRoutes';
import overtimeRoutes from '../routes/overtimeRoutes';
import timeEntryRoutes from '../routes/timeEntryRoutes';
import employeeDashboardRoutes from '../routes/employeeDashboardRoutes';
import alertRoutes from '../routes/alertRoutes';
import reportRoutes from '../routes/reportRoutes';
import reportScheduleRoutes from '../routes/reportScheduleRoutes';
import documentRoutes from '../routes/documentRoutes';
import expenseRoutes from '../routes/expenseRoutes';
import assetRoutes from '../routes/assetRoutes';
import checklistRoutes from '../routes/checklistRoutes';
import projectRoutes from '../routes/projectRoutes';
import employeeProjectWorkRoutes from '../routes/employeeProjectWorkRoutes';
import authRoutes from '../routes/authRoutes';
import userRoutes from '../routes/userRoutes';
import permissionProfileRoutes from '../routes/permissionProfileRoutes';
import documentTemplateRoutes from '../routes/documentTemplateRoutes';
import inboxRoutes from '../routes/inboxRoutes';
import configRoutes from '../routes/configRoutes';
import { inventoryRoutes } from '../routes/inventoryRoutes';
import notificationRoutes from '../routes/notificationRoutes';
import onboardingRoutes from '../routes/onboardingRoutes';
import anomalyRoutes from '../routes/anomalyRoutes';
import kioskRoutes from '../routes/kioskRoutes';
import offboardingRoutes from '../routes/offboardingRoutes';
import vehicleRoutes from '../routes/vehicleRoutes';
import cardRoutes from '../routes/cardRoutes';
import calendarRoutes from '../routes/calendarRoutes';
import analyticsRoutes from '../routes/analyticsRoutes';
import performanceRoutes from '../routes/performanceRoutes';
import lockRoutes from '../routes/lockRoutes';
import absenceTypeConfigRoutes from '../routes/absenceTypeConfigRoutes';
import consentRoutes from '../routes/consentRoutes';
import meRoutes from '../routes/meRoutes';

export function registerRoutes(app: Express): void {
    app.use('/api/kiosk', kioskRoutes);

    app.use('/api/auth', authRoutes);
    app.use('/api/users', userRoutes);
    app.use('/api/permission-profiles', permissionProfileRoutes);
    app.use('/api/document-templates', documentTemplateRoutes);
    app.use('/api/inbox', inboxRoutes);
    app.use('/api/config', configRoutes);
    app.use('/api/notifications', notificationRoutes);
    app.use('/api/anomalies', anomalyRoutes);
    app.use('/api/time-entries', timeEntryRoutes);
    app.use('/api/onboarding', onboardingRoutes);
    app.use('/api/offboarding', offboardingRoutes);
    app.use('/api/vehicles', vehicleRoutes);
    app.use('/api/cards', cardRoutes);
    app.use('/api/calendar', calendarRoutes);
    app.use('/api/analytics', analyticsRoutes);
    app.use('/api/inventory', inventoryRoutes);

    app.use('/api/dashboard/v2', protect, employeeDashboardRoutes);
    app.use('/api/employees', protect, employeeRoutes);
    app.use('/api/payroll', protect, payrollRoutes);
    app.use('/api/mappings', protect, checkPermission('payroll', 'write'), mappingProfileRoutes);
    app.use('/api/dashboard', protect, dashboardRoutes);
    app.use('/api/vacations', protect, vacationRoutes);
    app.use('/api/companies', protect, checkPermission('companies', 'read'), companyRoutes);
    app.use('/api/audit', protect, requireGlobalAdmin, auditRoutes);
    app.use('/api/overtime', protect, checkPermission('employees', 'read'), overtimeRoutes);
    app.use('/api/alerts', protect, alertRoutes);
    app.use('/api/reports', protect, checkPermission('reports', 'read'), reportRoutes);
    app.use('/api/report-schedules', protect, reportScheduleRoutes);
    app.use('/api/documents', protect, documentRoutes);
    app.use('/api/expenses', protect, expenseRoutes);
    app.use('/api/assets', protect, checkPermission('assets', 'read'), assetRoutes);
    app.use('/api/checklists', protect, checkPermission('employees', 'read'), checklistRoutes);
    app.use('/api/projects', protect, checkPermission('projects', 'read'), projectRoutes);
    app.use('/api/employee-project-work', protect, checkPermission('projects', 'read'), employeeProjectWorkRoutes);
    app.use('/api/performance', protect, performanceRoutes);
    app.use('/api/locks', protect, lockRoutes);
    app.use('/api/consents', protect, consentRoutes);
    app.use('/api/me', protect, meRoutes);
    app.use('/api/absence-types', absenceTypeConfigRoutes);
}
